# Fundamentos de PyTorch para Procesamiento de Lenguaje Natural

Este notebook está diseñado para estudiantes que comienzan con PyTorch y desean aplicarlo a tareas de NLP. Cubriremos desde los conceptos básicos de tensores hasta la construcción de un modelo simple de clasificación de texto.

## Contenido
1. Introducción a Tensores
2. Operaciones con Tensores
3. Indexación y reshaping
4. Autograd: Diferenciación automática
5. Construcción de modelos con `nn.Module`
6. Capas comunes en NLP: Embedding, Linear, activaciones
7. Funciones de pérdida y optimizadores
8. Creación de un Dataset y DataLoader
9. Ejemplo completo: Clasificación de sentimiento con una red feed-forward
10. Evaluación del modelo
11. Ejercicios propuestos


## 0. Verificación de instalación

Ejecuta la siguiente celda para verificar que PyTorch está instalado correctamente.

In [1]:
import torch
print("Versión de PyTorch:", torch.__version__)
print("¿CUDA disponible?", torch.cuda.is_available())

Versión de PyTorch: 2.10.0+cu128
¿CUDA disponible? True


## 1. Introducción a Tensores

Un tensor es una generalización de matrices y vectores a dimensiones superiores. En PyTorch, los tensores son similares a los arrays de NumPy, pero con la capacidad de ejecutarse en GPU y de registrar operaciones para el cálculo automático de gradientes.

In [2]:
# Crear un tensor desde una lista
tensor1 = torch.tensor([1, 2, 3, 4])
print("Tensor 1D:", tensor1)

# Tensor 2D (matriz)
tensor2 = torch.tensor([[1, 2], [3, 4]])
print("Tensor 2D:\n", tensor2)

# Tensor con valores aleatorios
tensor3 = torch.rand(3, 4)  # 3 filas, 4 columnas
print("Tensor aleatorio (3x4):\n", tensor3)

# Tensor de ceros
tensor_zeros = torch.zeros(2, 3)
print("Tensor de ceros:\n", tensor_zeros)

# Tensor de unos
tensor_ones = torch.ones(2, 3)
print("Tensor de unos:\n", tensor_ones)

# Tensor con valores específicos (tipo float)
tensor_float = torch.tensor([[1.5, 2.3], [4.0, 5.1]], dtype=torch.float32)
print("Tensor float:\n", tensor_float)

Tensor 1D: tensor([1, 2, 3, 4])
Tensor 2D:
 tensor([[1, 2],
        [3, 4]])
Tensor aleatorio (3x4):
 tensor([[0.9387, 0.5598, 0.2396, 0.8472],
        [0.5292, 0.1166, 0.3364, 0.9280],
        [0.9496, 0.6223, 0.4788, 0.4337]])
Tensor de ceros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor de unos:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor float:
 tensor([[1.5000, 2.3000],
        [4.0000, 5.1000]])


### Propiedades de los tensores
- `shape`: dimensiones
- `dtype`: tipo de dato
- `device`: CPU o GPU

In [3]:
t = torch.rand(3, 4, 5)
print("Forma (shape):", t.shape)
print("Número de dimensiones:", t.ndim)
print("Tipo de dato:", t.dtype)
print("Dispositivo:", t.device)

Forma (shape): torch.Size([3, 4, 5])
Número de dimensiones: 3
Tipo de dato: torch.float32
Dispositivo: cpu


## 2. Operaciones con Tensores

Las operaciones aritméticas se realizan elemento a elemento.

In [4]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación elemento a elemento:", a * b)
print("División:", a / b)
print("Potencia:", a ** 2)

# Funciones matemáticas
print("seno:", torch.sin(a))
print("exponencial:", torch.exp(a.float()))

Suma: tensor([5, 7, 9])
Resta: tensor([-3, -3, -3])
Multiplicación elemento a elemento: tensor([ 4, 10, 18])
División: tensor([0.2500, 0.4000, 0.5000])
Potencia: tensor([1, 4, 9])
seno: tensor([0.8415, 0.9093, 0.1411])
exponencial: tensor([ 2.7183,  7.3891, 20.0855])


### Broadcasting
Similar a NumPy, PyTorch permite operaciones entre tensores de diferentes formas automáticamente.

In [5]:
matriz = torch.tensor([[1, 2], [3, 4]])  # (2,2)
vector = torch.tensor([10, 20])          # (2,)
resultado = matriz + vector               # broadcasting: vector se convierte a (2,2)
print("Matriz + vector:\n", resultado)

Matriz + vector:
 tensor([[11, 22],
        [13, 24]])


## 3. Indexación y reshaping

Los tensores se indexan de manera similar a las listas de Python o arrays de NumPy.

In [6]:
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Tensor original:\n", t)
print("Primera fila:", t[0])
print("Última columna:", t[:, -1])
print("Submatriz (filas 0-1, columnas 1-2):\n", t[0:2, 1:3])

Tensor original:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Primera fila: tensor([1, 2, 3])
Última columna: tensor([3, 6, 9])
Submatriz (filas 0-1, columnas 1-2):
 tensor([[2, 3],
        [5, 6]])


In [7]:
# Cambiar forma
t = torch.arange(12)  # 0 a 11
print("Original:", t)
t_reshaped = t.view(3, 4)  # 3 filas, 4 columnas
print("Reshape a (3,4):\n", t_reshaped)

# Aplanar
t_flat = t_reshaped.view(-1)  # -1 infiere la dimensión
print("Aplanado:", t_flat)

# Transponer
t_t = t_reshaped.T
print("Transpuesta:\n", t_t)

Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshape a (3,4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Aplanado: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Transpuesta:
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


## 4. Autograd: Diferenciación automática

La característica más importante de PyTorch es el cálculo automático de gradientes. Para ello, los tensores deben tener `requires_grad=True`.

In [8]:
x = torch.tensor([2.0], requires_grad=True)
y = x ** 2 + 3*x + 1
print("y:", y)

# Calcular gradiente dy/dx
y.backward()
print("Gradiente dy/dx:", x.grad)  # Derivada: 2x + 3, en x=2 → 7

y: tensor([11.], grad_fn=<AddBackward0>)
Gradiente dy/dx: tensor([7.])


### Ejemplo con múltiples variables

In [9]:
a = torch.tensor([1.0, 2.0], requires_grad=True)
b = torch.tensor([3.0, 4.0], requires_grad=True)
z = (a * b).sum()  # producto punto
z.backward()
print("Gradiente de a:", a.grad)  # = b
print("Gradiente de b:", b.grad)  # = a

Gradiente de a: tensor([3., 4.])
Gradiente de b: tensor([1., 2.])


## 5. Construcción de modelos con `nn.Module`

Los modelos en PyTorch se definen como clases que heredan de `nn.Module`. Deben implementar el método `forward`.

In [10]:
import torch.nn as nn

class ModeloLineal(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.linear(x)

# Instanciar modelo
modelo = ModeloLineal(10, 2)
print(modelo)

# Parámetros del modelo
for nombre, param in modelo.named_parameters():
    print(f"{nombre}: {param.shape}")

ModeloLineal(
  (linear): Linear(in_features=10, out_features=2, bias=True)
)
linear.weight: torch.Size([2, 10])
linear.bias: torch.Size([2])


## 6. Capas comunes en NLP

### Capa Embedding
Convierte índices de palabras en vectores densos.

In [11]:
embedding = nn.Embedding(num_embeddings=100, embedding_dim=50)  # vocab_size=100, dim=50
indices = torch.tensor([1, 5, 23, 7])  # secuencia de 4 palabras
embedded = embedding(indices)  # (4, 50)
print("Embedding output shape:", embedded.shape)

Embedding output shape: torch.Size([4, 50])


### Capa Lineal (Fully Connected)
`nn.Linear(in_features, out_features)`

In [12]:
linear = nn.Linear(50, 20)
x = torch.rand(3, 50)  # batch de 3 muestras
out = linear(x)
print("Salida lineal shape:", out.shape)  # (3, 20)

Salida lineal shape: torch.Size([3, 20])


### Funciones de activación
Se aplican después de las capas lineales.

In [13]:
relu = nn.ReLU()
tanh = nn.Tanh()
sigmoid = nn.Sigmoid()

z = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
print("ReLU:", relu(z))
print("Tanh:", tanh(z))
print("Sigmoid:", sigmoid(z))

ReLU: tensor([0., 0., 0., 1., 2.])
Tanh: tensor([-0.9640, -0.7616,  0.0000,  0.7616,  0.9640])
Sigmoid: tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])


## 7. Funciones de pérdida y optimizadores

### Funciones de pérdida
Para clasificación, usamos `CrossEntropyLoss`.

In [14]:
criterion = nn.CrossEntropyLoss()

# Ejemplo: logits (predicciones sin softmax) y etiquetas
logits = torch.tensor([[2.0, 0.5, 0.1], [0.1, 2.0, 0.3]])  # batch de 2, 3 clases
labels = torch.tensor([0, 1])  # clase correcta para cada muestra
loss = criterion(logits, labels)
print("Pérdida:", loss.item())

Pérdida: 0.30182474851608276


### Optimizadores
Actualizan los parámetros del modelo usando los gradientes.

In [15]:
optimizer = torch.optim.Adam(modelo.parameters(), lr=0.001)

# Ciclo típico:
# optimizer.zero_grad()  # limpia gradientes anteriores
# loss.backward()        # calcula gradientes
# optimizer.step()       # actualiza parámetros

## 8. Creación de un Dataset y DataLoader

Para manejar datos de texto, creamos una clase que herede de `torch.utils.data.Dataset`.

In [16]:
from torch.utils.data import Dataset, DataLoader

class TextDataset(Dataset):
    def __init__(self, texts, labels, vocab, max_len=10):
        self.texts = texts
        self.labels = labels
        self.vocab = vocab
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        # Convertir texto a índices (ejemplo simple)
        tokens = self.texts[idx].lower().split()
        indices = [self.vocab.get(t, 1) for t in tokens[:self.max_len]]  # 1 = <UNK>
        # Padding
        indices += [0] * (self.max_len - len(indices))  # 0 = <PAD>
        return torch.tensor(indices), torch.tensor(self.labels[idx])

# Datos de ejemplo
texts = ["I love this movie", "Terrible film"]
labels = [1, 0]
vocab = {'<PAD>':0, '<UNK>':1, 'i':2, 'love':3, 'this':4, 'movie':5, 'terrible':6, 'film':7}

dataset = TextDataset(texts, labels, vocab, max_len=5)
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

for batch_x, batch_y in dataloader:
    print("Batch x:", batch_x)
    print("Batch y:", batch_y)

Batch x: tensor([[2, 3, 4, 5, 0],
        [6, 7, 0, 0, 0]])
Batch y: tensor([1, 0])


## 9. Ejemplo completo: Clasificación de sentimiento con red feed-forward

Construiremos un modelo simple que promedia los embeddings de las palabras y pasa el resultado por un MLP.

In [17]:
class SentimentClassifier(nn.Module):
    def __init__(self, vocab_size, embed_dim=50, hidden_dim=32, num_classes=2, dropout=0.5):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.fc1 = nn.Linear(embed_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, num_classes)
        self.dropout = nn.Dropout(dropout)
        self.relu = nn.ReLU()

    def forward(self, x):
        # x: (batch, seq_len)
        embedded = self.embedding(x)          # (batch, seq_len, embed_dim)
        pooled = embedded.mean(dim=1)         # (batch, embed_dim)  # average pooling
        h = self.dropout(self.relu(self.fc1(pooled)))  # (batch, hidden_dim)
        out = self.fc2(h)                     # (batch, num_classes)
        return out

In [18]:
# Crear vocabulario pequeño
texts_ejemplo = [
    "I loved this movie it was fantastic",
    "Terrible film I hated it",
    "Amazing acting and great story",
    "Boring and slow waste of time"
]
labels_ejemplo = [1, 0, 1, 0]

# Construir vocabulario (solo para este ejemplo)
from collections import Counter
word_counts = Counter()
for text in texts_ejemplo:
    word_counts.update(text.lower().split())
vocab = {word: i+2 for i, (word, _) in enumerate(word_counts.items())}
vocab['<PAD>'] = 0
vocab['<UNK>'] = 1
print("Vocabulario:", vocab)

dataset_ejemplo = TextDataset(texts_ejemplo, labels_ejemplo, vocab, max_len=8)
dataloader_ejemplo = DataLoader(dataset_ejemplo, batch_size=2, shuffle=True)

Vocabulario: {'i': 2, 'loved': 3, 'this': 4, 'movie': 5, 'it': 6, 'was': 7, 'fantastic': 8, 'terrible': 9, 'film': 10, 'hated': 11, 'amazing': 12, 'acting': 13, 'and': 14, 'great': 15, 'story': 16, 'boring': 17, 'slow': 18, 'waste': 19, 'of': 20, 'time': 21, '<PAD>': 0, '<UNK>': 1}


In [19]:
# Inicializar modelo, pérdida y optimizador
model = SentimentClassifier(vocab_size=len(vocab), embed_dim=20, hidden_dim=16, num_classes=2)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# Entrenamiento por épocas
epochs = 50
for epoch in range(epochs):
    total_loss = 0
    for batch_x, batch_y in dataloader_ejemplo:
        optimizer.zero_grad()
        logits = model(batch_x)
        loss = criterion(logits, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    if (epoch+1) % 10 == 0:
        print(f"Época {epoch+1}, Pérdida promedio: {total_loss/len(dataloader_ejemplo):.4f}")

Época 10, Pérdida promedio: 0.5288
Época 20, Pérdida promedio: 0.3971
Época 30, Pérdida promedio: 0.0471
Época 40, Pérdida promedio: 0.0127
Época 50, Pérdida promedio: 0.2358


## 10. Evaluación del modelo

Calculamos precisión en el mismo conjunto (solo con fines ilustrativos).

In [20]:
with torch.no_grad():
    correct = 0
    total = 0
    for batch_x, batch_y in dataloader_ejemplo:
        logits = model(batch_x)
        preds = torch.argmax(logits, dim=1)
        correct += (preds == batch_y).sum().item()
        total += batch_y.size(0)
    print(f"Precisión: {correct/total:.2%}")

Precisión: 100.00%


## 11. Ejercicios propuestos

1. Cambia la función de pooling de promedio a max-pooling. ¿Cómo afecta al rendimiento?
2. Añade una capa oculta adicional al MLP.
3. Prueba diferentes funciones de activación (tanh, sigmoid) en la capa oculta.
4. Utiliza un conjunto de datos real (por ejemplo, de sklearn o descarga uno de reseñas) y adapta el pipeline.
5. Implementa una máscara para ignorar el padding en el promedio (en lugar de usar `mean` directamente).

---

¡Felicidades! Has completado los fundamentos de PyTorch para NLP. Este conocimiento te permitirá abordar arquitecturas más complejas como RNNs, LSTMs y Transformers en las próximas sesiones.